### ISSUE TITLE
Error:  0x80004003 - Invalid pointer Source:		SciterSharpWindows Description:	Object reference not set to an instance of an object.  Specifically: CreateMainWindow

### ISSUE THREAD

**Issue by FuPeiJiang** [GirkovArpa/ahk-sciter-js#1]
hi, I'm coming from https://github.com/FuPeiJiang/ahk_parser.js/issues/22

I've cloned the repo

I've downloaded
`sciter.dll`                            8.23MB
`SciterSharpWindows.dll` 161.50KB
I've copied these files into the folder `ahk-sciter-js\`

I run using `AutoHotkeyU64.exe` with WorkingDir `ahk-sciter-js\`
note: that was AHK_L v1 version 1.1.33.09

I'm getting this error
```
---------------------------
main.ahk
---------------------------
Error:  0x80004003 - Invalid pointer
Source:		SciterSharpWindows
Description:	Object reference not set to an instance of an object.
HelpFile:		(null)
HelpContext:	0

Specifically: CreateMainWindow

	Line#
	148: {
	149: VarSetCapacity(GUID, 16, 0)  
	150: Return,DllCall("ole32\CLSIDFromString", "wstr", sGUID, "ptr", &GUID) >= 0 ? &GUID : ""
	151: }
	011: FileRead,html,main.html
	013: sci := Clr_LoadLibrary("SciterSharpWindows.dll")
	014: sciwin := Clr_CreateObject(sci, "SciterSharp.SciterWindow")
--->	015: sciwin.CreateMainWindow(400, 300)  
	016: sciwin.CenterTopLevelWindow()  
	017: sciwin.Title := "Using SciterSharp in AutoHotkey"  
	018: sciwin.LoadHtml(html)  
	019: sciwin.Show()  
	020: Return
	022: Return
	024: Return

Continue running the script?
---------------------------
Yes   No   
---------------------------
```
can you explain this error ?

using a debugger: I look at variables:
`sci`
```
Assembly
  Value:91946016
  VarType:9
  DispatchType:"_Assembly"
  DispatchIID:"{17156360-2F1A-384A-BC52-FDE93C215C5B}"
```
`sciwin`
```
Object
  Value:91945752
  VarType:9
  DispatchType:"IUnknown"
  DispatchIID:"{00000000-0000-0000-C000-000000000046}"
```

`sciwin` DispatchIID doesn't seem normal: it has too many zeros

**Comment by GirkovArpa** [comment]
Sciter is constantly undergoing breaking changes.  Fortunately [this older version](https://github.com/c-smile/sciter-js-sdk/blob/e1909ed966b585466bd235994f00a80ed58f30df/bin/windows/x64/sciter.dll) should work.  It was current at the time I made this repo.

**Comment by FuPeiJiang** [comment]
thank you, works now

https://www.fuget.org/packages/SciterSharpWindows/3.0.0/lib/net45/SciterSharpWindows.dll/SciterSharp/SciterWindow
I can see the methods

so are we dependent on SciterSharpWindows ?
even if we changed to the updated method names, it still wouldn't work? because we need SciterSharpWindows to call them?

**Comment by GirkovArpa** [comment]
It does appear to be dependent on SciterSharpWindows, yes.  I am not sure what "updated method names" refers to.  Are you trying to use the latest version of Sciter?

**Comment by FuPeiJiang** [comment]
sorry, I assumed that the breaking changes were that "the method names were changed to something else"
and it's not a method name, it's a class name `SciterWindow`
I assumed that `SciterWindow` was renamed, that's why it didn't work

but I have no clue what actually changed (what are the breaking changes)

> Are you trying to use the latest version of Sciter?

I won't try, I just need a working AHK_v1 script, to be able to verify if AHK_v2 conversion works correctly

**Comment by GirkovArpa** [comment]
I am not sure what the breaking changes are either.  In such cases I usually just download the required version and call it a day 😄

**Comment by FuPeiJiang** [comment]
can you update README ?
change
`[sciter.dll](https://github.com/c-smile/sciter-js-sdk/blob/main/bin/windows/x64/sciter.dll)`
to
`[sciter.dll](https://github.com/c-smile/sciter-js-sdk/blob/e1909ed966b585466bd235994f00a80ed58f30df/bin/windows/x64/sciter.dll)`

"newest version of `sciter.dll` has breaking changes, this version should work"
